### PR TITLE
add wasm32 and wasm64 flags for ad

### PR DESCRIPTION
**Pull request by th0br0**

### CODE REVIEW

**Comment by japaric** [comment]
Thank you @th0br0.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 40007c5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 40007c5 with merge 40007c5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cty/builds/247794395?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 40007c54615889880cf082ea42eda2b9f5c974cd to master...

**Pull request merged**
