### PR TITLE
Include additional types from libc

### PR DESCRIPTION
**Pull request by Amanieu**
Copied a few extra definitions from the libc crate.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @Amanieu.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f9ab9f9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f9ab9f9fe7b600f7eb5259d48137b0b337876fdc with merge 4d8b2525ae6adcd5a2cd09ec575234f0f65a1a80...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cty/builds/287449704?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 4d8b2525ae6adcd5a2cd09ec575234f0f65a1a80 to master...

**Pull request merged**
