### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6c6bc6d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6c6bc6d with merge 6c6bc6d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cty/builds/237278724?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2aaded4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2aaded4 with merge 2aaded4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cty/builds/237279241?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2aaded4699af5b8bbd26aa5e145e8cce9283fecc to master...

**Pull request merged**
