### PR TITLE
add more types

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1e7a8d1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1e7a8d1 with merge 1e7a8d1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cty/builds/237280427?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 1e7a8d1997b2a59d4a39bc18d1dab226e67d135f to master...

**Pull request merged**
